
CREATE TABLE Student (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    firstName NVARCHAR(50) NOT NULL,
    lastName NVARCHAR(50) NOT NULL,
    age INT NOT NULL,
    major NVARCHAR(50) NOT NULL
);



INSERT INTO Student (firstName, lastName, age, major)
VALUES
    ('Irvin', 'Ruacho', 20, 'Computer Science'),
    ('Luis', 'Smith', 22, 'Mathematics'),
    ('Angel', 'Ruiz', 19, 'Biology'),
    ('Cynthia', 'Hernandez', 21, 'Engineering'),
    ('David', 'Garcia', 23, 'Economics'),
    ('Sophia', 'Cortes', 20, 'Psychology'),
    ('Jose', 'Martinez', 22, 'Physics'),
    ('Isabella', 'Jackson', 19, 'Chemistry'),
    ('Noah', 'Rojas', 21, 'Philosophy'),
    ('Mia', 'Martinez', 23, 'Business Administration'),
	('Rosalinda', 'Martinez', 20, 'Computer Science'),
    ('Rocio', 'Ramirez', 22, 'Mathematics'),
    ('Roberto', 'Castillo', 19, 'Biology'),
    ('Efrain', 'Rojas', 21, 'Engineering'),
    ('Ernesto', 'Chavez', 23, 'Economics'),
    ('Maria', 'Rodriguez', 20, 'Psychology'),
    ('Martin', 'Torres', 22, 'Physics'),
    ('Irma', 'Avila', 19, 'Chemistry'),
    ('Arturo', 'Lomas', 21, 'Philosophy'),
    ('Janeth', 'Martinez', 23, 'Business Administration'),
	('Perla', 'Sanchez', 21, 'Philosophy'),
    ('Karina', 'Torres', 23, 'Business Administration'),
	('Mariela', 'Ruacho', 20, 'Computer Science'),
    ('Antonio', 'Lomas', 22, 'Mathematics'),
    ('Ricardo', 'Martinez', 19, 'Biology'),
    ('Marcela', 'Gonzalez', 21, 'Engineering'),
    ('Maximiliano', 'Chavez', 23, 'Economics'),
    ('Monica', 'Rodriguez', 20, 'Psychology'),
    ('Guillermo', 'Rodriguez', 22, 'Physics'),
    ('Sara', 'Rodriguez', 19, 'Chemistry'),
    ('Erika', 'Garcia', 21, 'Philosophy'),
    ('Pedro', 'Lopez', 23, 'Business Administration'),
	('Natalia', 'Lopez', 21, 'Philosophy'),
    ('Sergio', 'Perez', 23, 'Business Administration'),
	('Diana', 'Sanchez', 20, 'Computer Science'),
    ('Estela', 'Ramirez', 22, 'Mathematics'),
    ('Rosa', 'Cruz', 19, 'Biology'),
    ('Sanjuana', 'Castillo', 21, 'Engineering'),
    ('Martha', 'Flores', 23, 'Economics'),
    ('Luis', 'Lopez', 20, 'Psychology'),
    ('Carlos', 'Ramirez', 22, 'Physics'),
    ('Edwin', 'Flores', 19, 'Chemistry'),
    ('Lizbeth', 'Gomez', 21, 'Philosophy'),
    ('Sebastian', 'Morales', 23, 'Business Administration'),
	('Emiliano', 'Vazquez', 21, 'Philosophy'),
    ('Gabriel', 'Reyes', 23, 'Business Administration'),
	('Miguel', 'Jimenez', 20, 'Computer Science'),
    ('Manuel', 'Diaz', 22, 'Mathematics'),
    ('Alejandro', 'Gutierrez', 19, 'Biology'),
    ('Bnjamin', 'Medoza', 21, 'Engineering'),
    ('Bruno', 'Chavez', 23, 'Economics'),
    ('Daniel', 'Rodriguez', 20, 'Psychology'),
    ('Diego', 'Torres', 22, 'Physics'),
    ('Emmanuel', 'Avila', 19, 'Chemistry'),
    ('Manuel', 'Lomas', 21, 'Philosophy'),
    ('Gael', 'Martinez', 23, 'Business Administration');

